version: '3.5'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.8-arm64
    #      docker.elastic.co/logstash/logstash-oss:8.1.2-arm64
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf
    networks:
      -   elk-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2-arm64
    environment:
      discovery.type: single-node
#        ES_JAVA_OPTS: -Xms750m -Xmx750m
    ports:
      - '9200:9200'
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data
    networks:
      -   elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2-arm64
    platform: "linux/amd64"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      -   elk-network



  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.2-arm64
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash
    networks:
      - elk-network

networks:
  elk-network:
    external:
      name: movie-network
