name: tg-notify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Success status
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |  
          ${{ github.event_name }} commit (status: success) in ${{ github.repository }} by "${{ github.actor }}". [${{github.sha}}@${{ github.ref }}]
